//random ending 2
//lake + paddleboarding

package EndingChapter;

import EndingChapter.RandomEndingOne;
import OpeningChapter.FirstPage;
import OpeningChapter.FirstPage;
import business.Person;
import business.RandomObject;
import javax.swing.JFrame;

public class RandomEndingTwo extends javax.swing.JFrame {
    
    public RandomEndingTwo() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public RandomEndingTwo(Person p) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
       
        String name = p.getName();
        String show = p.getShow();
        String subject = p.getSubject();
        String age = p.getAge();
        
        
        passedName.setText(name);
        passedShow.setText(show);
        passedSubject.setText(subject);
        passedAge.setText(age);
        
        txtAreaRE2.setText("Hey " + name + "!"
                + "\nIt's been a really fun day!"
                + "\nLet's finish the day off on paddleboards at the lake");
        
        passedCounter.setText("Do you want to read again? "
                + "\n(Type yes or no)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        passedCounter = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaRE2 = new javax.swing.JTextArea();
        Continue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        passedName = new javax.swing.JLabel();
        passedShow = new javax.swing.JLabel();
        passedSubject = new javax.swing.JLabel();
        passedAge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passedCounter.setColumns(20);
        passedCounter.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        passedCounter.setRows(5);
        jPanel1.add(passedCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 620, -1, 80));

        txtAreaRE2.setColumns(20);
        txtAreaRE2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtAreaRE2.setRows(5);
        txtAreaRE2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 8));
        jScrollPane1.setViewportView(txtAreaRE2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 640, 130));

        Continue.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Continue.setText("Yes/No");
        Continue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContinueMouseEntered(evt);
            }
        });
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });
        jPanel1.add(Continue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 730, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningChapter/Photos/lakepaddleboarding.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 1250, 830));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 830));

        passedName.setText("passedName");
        getContentPane().add(passedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        passedShow.setText("passedShow");
        getContentPane().add(passedShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        passedSubject.setText("passedSubject");
        getContentPane().add(passedSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        passedAge.setText("passedAge");
        getContentPane().add(passedAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
                
        String answer = Continue.getText();
        
        if(answer.equalsIgnoreCase("Yes")){            
            String name = passedName.getText();
            String show = passedShow.getText();
            String subject = passedSubject.getText();
            String age = passedAge.getText();
            
            passedCounter.setText("1");
            String count = passedCounter.getText();
            Person p = new Person(name, show, subject, age, count);
            new FirstPage(p).setVisible(true);
            
        }
    }//GEN-LAST:event_ContinueActionPerformed

    private void ContinueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueMouseEntered
        Continue.setText("");
    }//GEN-LAST:event_ContinueMouseEntered

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RandomEndingOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RandomEndingOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RandomEndingOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RandomEndingOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RandomEndingTwo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Continue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel passedAge;
    private javax.swing.JTextArea passedCounter;
    private javax.swing.JLabel passedName;
    private javax.swing.JLabel passedShow;
    private javax.swing.JLabel passedSubject;
    private javax.swing.JTextArea txtAreaRE2;
    // End of variables declaration//GEN-END:variables
}
