//park
//I SPY

package Park;

import Storytime.PageFourStorytime;
import EndingChapter.RandomEndingOne;
import OpeningChapter.Coverpage;
import business.Person;
import business.RandomObject;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class PageThreePark extends javax.swing.JFrame {


    public PageThreePark() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public PageThreePark(Person p) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
       
        String name = p.getName();
        String show = p.getShow();
        String subject = p.getSubject();
        String age = p.getAge();
        
        
        passedName.setText(name);
        passedShow.setText(show);
        passedSubject.setText(subject);
        passedAge.setText(age);
        
        textAreaPageThree.setText("Welcome to my favorite place " + name + "!"
                + "\nThis is the park!"
                + "\nOut here, I like to run with the other dogs, chase the squirrels, and my most favorite is playing I SPY!"
                + "\nSo, let's play! What do you think I'm looking at?"
                + "\nIt's either: dog, chairs, hay, or grass!"
                + "\nIf you guess correctly, I'll send you to our next spot!");
        
        RandomObject o = new RandomObject();
        
        String nameCompare = o.getRandomName();
        textFieldPageThree.setText(nameCompare);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaPageThree = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        yourGuessTextFieldPageThree = new javax.swing.JTextField();
        backToHomeButton = new javax.swing.JButton();
        passedName = new javax.swing.JLabel();
        passedShow = new javax.swing.JLabel();
        passedSubject = new javax.swing.JLabel();
        passedAge = new javax.swing.JLabel();
        textFieldPageThree = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1540, 830));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(202, 240, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningChapter/Photos/colbyJackParkPicResized.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 10), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 25, -1, 613));

        textAreaPageThree.setColumns(20);
        textAreaPageThree.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textAreaPageThree.setRows(5);
        textAreaPageThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jScrollPane1.setViewportView(textAreaPageThree);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 649, 937, 135));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Your Guess:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1064, 697, 193, 57));

        yourGuessTextFieldPageThree.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        yourGuessTextFieldPageThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        yourGuessTextFieldPageThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourGuessTextFieldPageThreeActionPerformed(evt);
            }
        });
        jPanel1.add(yourGuessTextFieldPageThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(1267, 687, 211, 78));

        backToHomeButton.setBackground(new java.awt.Color(204, 255, 204));
        backToHomeButton.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        backToHomeButton.setText("Back to Home");
        backToHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToHomeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backToHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1281, 307, -1, 52));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 830));

        passedName.setText("passedName");
        getContentPane().add(passedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        passedShow.setText("passedShow");
        getContentPane().add(passedShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        passedSubject.setText("passedSubject");
        getContentPane().add(passedSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        passedAge.setText("passedAge");
        getContentPane().add(passedAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(textFieldPageThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(1349, 474, 118, 34));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomeButtonActionPerformed
        new Coverpage().setVisible(true);
        this.setVisible(false);                                     
    }//GEN-LAST:event_backToHomeButtonActionPerformed

    private void yourGuessTextFieldPageThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourGuessTextFieldPageThreeActionPerformed
        RandomObject o = new RandomObject();
        String name = passedName.getText();
        String show = passedShow.getText();
        String subject = passedSubject.getText();
        String age = passedAge.getText();
        Person p = new Person(name, show, subject, age);
        String nameCompare = textFieldPageThree.getText();
        
        if(yourGuessTextFieldPageThree.getText().isEmpty()){
            JOptionPane.showMessageDialog(yourGuessTextFieldPageThree, "Please enter a guess");
        }else if(yourGuessTextFieldPageThree.getText().equalsIgnoreCase(nameCompare)){
            JOptionPane.showMessageDialog(yourGuessTextFieldPageThree, "Your answer is correct!");
            new Park2(p).setVisible(true);
            this.setVisible(false);
        }else{
            yourGuessTextFieldPageThree.setText("");
            JOptionPane.showMessageDialog(yourGuessTextFieldPageThree, "Your answer is incorrect! Try again");
            
            if(yourGuessTextFieldPageThree.getText().equalsIgnoreCase(nameCompare)){
                JOptionPane.showMessageDialog(yourGuessTextFieldPageThree, "Your answer is correct!");
                new Park2(p).setVisible(true);
                this.setVisible(false);
            }
        }
        
                
    }//GEN-LAST:event_yourGuessTextFieldPageThreeActionPerformed
        
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RandomEndingOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RandomEndingOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RandomEndingOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RandomEndingOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageThreePark().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToHomeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel passedAge;
    private javax.swing.JLabel passedName;
    private javax.swing.JLabel passedShow;
    private javax.swing.JLabel passedSubject;
    private javax.swing.JTextArea textAreaPageThree;
    private javax.swing.JTextField textFieldPageThree;
    private javax.swing.JTextField yourGuessTextFieldPageThree;
    // End of variables declaration//GEN-END:variables
}
