//slideshow of park riddle answers

//ADD THREE DOTS ABOVE COLBY'S HEAD

package Park;

import Storytime.*;
import EndingChapter.RandomEndingOne;
import business.Person;
import business.RandomObject;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.Timer;

public class Park3 extends javax.swing.JFrame {

    public Park3() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public Park3(Person p) {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        
        Timer tm = new Timer(1000, (ActionEvent e) -> {
            storypg1.setVisible(true);
            storypg2.setVisible(false);
            storypg3.setVisible(false);
            storypg4.setVisible(false);
            
            txtArea.setText(" Ha, I thought you'd get this one right!"
                    + "\n It's a bench, like one that I always "
                    + "\n see at the park."
                    + "\n But, I've never actually sat on one "
                    + "\n of those,"
                    + "\n even though I see them everywhere"
                    + "\n maybe one day...");
            
                
        });
        tm.start();   
        
        Timer tm1 = new Timer(4000, (ActionEvent e) -> {
            tm.stop();
            
            storypg1.setVisible(false);
            storypg2.setVisible(true);
            storypg3.setVisible(false);
            storypg4.setVisible(false);
            
            txtArea.setText(" Got this one correct too!?!"
                    + "\n Alrighty, these were the easy ones."
                    + "\n I know what that is too!"
                    + "\n It's a fence."
                    + "\n Well, some people call it a gate."
                    + "\n I guess whatever works for you!");
            
        });
        tm1.start();
        
        Timer tm2 = new Timer(8000, (ActionEvent e) -> {
            tm1.stop();
            
            storypg1.setVisible(false);
            storypg2.setVisible(false);
            storypg3.setVisible(true);
            storypg4.setVisible(false);
            
            txtArea.setText(" Now this one was a lot harder!"
                    + "\n It's one of my favorite riddles:"
                    + "\n What has two ends and no beginning?"
                    + "\n It's also my favorite toy, duh!!"
                    + "\n It's a rope!");
                              
        });
        tm2.start();
        
        Timer tm3 = new Timer(12000, (ActionEvent e) -> {
            tm2.stop();
            
            storypg1.setVisible(false);
            storypg2.setVisible(false);
            storypg3.setVisible(false);
            storypg4.setVisible(true);
            
            txtArea.setText(" Alrighty, when I first heard this "
                    + "\n riddle,"
                    + "\n I had no idea either."
                    + "\n But, I'm sure you figured it out super "
                    + "\n quick!"
                    + "\n I think it goes something like this:"
                    + "\n I am a ball that can be rolled,"
                    + "\n but never bounced or thrown."
                    + "\n It's an eyeball, obviously!!");
        });
        tm3.start();
        
        Timer tm4 = new Timer(21000, (ActionEvent e) -> {
            tm3.stop();
            
            RandomObject o = new RandomObject();
            o.getRandomEnding(p);
        });
        tm4.start();
        
        Timer tm5 = new Timer(22000, (ActionEvent e) -> {
            tm4.stop();
        });
        tm5.start();
        
        Timer tm6 = new Timer(22500, (ActionEvent e) -> {
            tm5.stop();
            
        });
        tm6.start();
    } 
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        storypg1 = new javax.swing.JLabel();
        storypg2 = new javax.swing.JLabel();
        storypg3 = new javax.swing.JLabel();
        storypg4 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        storypg1.setBackground(new java.awt.Color(204, 204, 255));
        storypg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningChapter/Photos/bench.jpg"))); // NOI18N
        jPanel1.add(storypg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 700, 700));

        storypg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningChapter/Photos/fence.png"))); // NOI18N
        jPanel1.add(storypg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 810, 480));

        storypg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningChapter/Photos/rope.jpeg"))); // NOI18N
        jPanel1.add(storypg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 680, 720));

        storypg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningChapter/Photos/eyeball.jpeg"))); // NOI18N
        jPanel1.add(storypg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 650, 650));

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtArea.setRows(5);
        txtArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jPanel1.add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 610, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningChapter/Photos/cjBaby2edited.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 370, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RandomEndingOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RandomEndingOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RandomEndingOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RandomEndingOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Park3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel storypg1;
    private javax.swing.JLabel storypg2;
    private javax.swing.JLabel storypg3;
    private javax.swing.JLabel storypg4;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
