//riddles about park 
//answer1: "bench" OR "a bench"
//answer2: "fence" OR "a fence" OR "gate" OR "a gate"
//answer3: "rope" OR "a rope"
//answer4: "eyeball" OR "an eyeball"

package Park;

import Library.*;
import OpeningChapter.Coverpage;
import OpeningChapter.FirstPage;
import business.Person;
import business.RandomObject;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Park2 extends javax.swing.JFrame {

    
    public Park2() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public Park2(Person p){
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        String name = p.getName();
        String show = p.getShow();
        String subject = p.getSubject();
        String age = p.getAge();
        
        
        passedName.setText(name);
        passedShow.setText(show);
        passedSubject.setText(subject);
        passedAge.setText(age);
        
        txtArea.setText("I have a few riddles for you about the park if you dare to "
                + "\nanswer them."
                + "\nThe last one is a trick one, so pay close attention, "
                + "\nand I'll be surprised if you get it!"
                + "\nAll of the answers will be shown on the next pages,"
                + "\nbut you have to correctly guess all the riddles to get there "
                + "\nand see them!");
        
        txtAreaR1.setText("  I'm found in the garden "
                + "\n  or in the park,"
                + "\n  Sometimes even on the "
                + "\n  sidewalk."
                + "\n  You can sit on me and eat "
                + "\n  your lunch"
                + "\n  Or maybe even eat some "
                + "\n  brunch!");
                        
        txtAreaR2.setText("  I guard the park from "
                + "\n  strangers outside."
                + "\n  I'm made of wood or metal, "
                + "\n  and I stretch wide."
                + "\n  Opening and closing is "
                + "\n  what I do."
                + "\n  I could have one entrance"
                + "\n  or maybe even two!");
                
        txtAreaR3.setText("  I have two ends but "
                + "\n  no beginning."
                + "\n  What am I??");
        
        txtAreaR4.setText("  I am a ball that can be "
                + "\n  rolled, but never bounced" 
                + "\n  or thrown."
                + "\n  What am I??");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtArea = new javax.swing.JTextArea();
        backToHomeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAreaR1 = new javax.swing.JTextArea();
        txtAreaR2 = new javax.swing.JTextArea();
        txtAreaR3 = new javax.swing.JTextArea();
        txtAreaR4 = new javax.swing.JTextArea();
        txtField1 = new javax.swing.JTextField();
        txtField2 = new javax.swing.JTextField();
        txtField3 = new javax.swing.JTextField();
        txtField4 = new javax.swing.JTextField();
        passedName = new javax.swing.JLabel();
        passedShow = new javax.swing.JLabel();
        passedSubject = new javax.swing.JLabel();
        passedAge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txtArea.setRows(5);
        txtArea.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 6)));
        jPanel1.add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 760, 250));

        backToHomeButton.setBackground(new java.awt.Color(204, 255, 204));
        backToHomeButton.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        backToHomeButton.setText("Back to Home");
        backToHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToHomeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backToHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 150, 250, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Your Guess:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 650, 170, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Your Guess:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 170, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Your Guess:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 650, 170, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Your Guess:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 600, 170, 40));

        txtAreaR1.setColumns(20);
        txtAreaR1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        txtAreaR1.setRows(5);
        txtAreaR1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 6));
        jPanel1.add(txtAreaR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 330, 230));

        txtAreaR2.setColumns(20);
        txtAreaR2.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        txtAreaR2.setRows(5);
        txtAreaR2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 6));
        jPanel1.add(txtAreaR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 330, 230));

        txtAreaR3.setColumns(20);
        txtAreaR3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        txtAreaR3.setRows(5);
        txtAreaR3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 6));
        jPanel1.add(txtAreaR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 320, 230));

        txtAreaR4.setColumns(20);
        txtAreaR4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        txtAreaR4.setRows(5);
        txtAreaR4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 6));
        jPanel1.add(txtAreaR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 400, 320, 230));

        txtField1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 6));
        txtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, 210, 60));

        txtField2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 6));
        txtField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 700, 210, 60));

        txtField3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 6));
        txtField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 650, 210, 60));

        txtField4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 6));
        txtField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField4ActionPerformed(evt);
            }
        });
        jPanel1.add(txtField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 700, 210, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 830));

        passedName.setText("passedName");
        getContentPane().add(passedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        passedShow.setText("passedShow");
        getContentPane().add(passedShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        passedSubject.setText("passedSubject");
        getContentPane().add(passedSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        passedAge.setText("passedAge");
        getContentPane().add(passedAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomeButtonActionPerformed
        new Coverpage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backToHomeButtonActionPerformed

        
    private void txtField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField4ActionPerformed
        String name = passedName.getText();
        String show = passedShow.getText();
        String subject = passedSubject.getText();
        String age = passedAge.getText();
        Person p = new Person(name, show, subject, age);
        
        if(txtField4.getText().isEmpty()){
            JOptionPane.showMessageDialog(txtField4, "Please enter a guess");
        }else if(txtField4.getText().equalsIgnoreCase("eyeball") || txtField4.getText().equalsIgnoreCase("an eyeball")){
            JOptionPane.showMessageDialog(txtField4, "Your answer is correct!");
            new Park3(p).setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(txtField4, "Your answer is incorrect. Try again!");
            txtField4.setText("");
            
            if(txtField4.getText().equalsIgnoreCase("an eyeball") || txtField4.getText().equalsIgnoreCase("eyeball")){
            JOptionPane.showMessageDialog(txtField4, "Your answer is correct!");
            new Park3(p).setVisible(true);
            this.setVisible(false);
            }
        }
    }//GEN-LAST:event_txtField4ActionPerformed

    private void txtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField1ActionPerformed
        String name = passedName.getText();
        String show = passedShow.getText();
        String subject = passedSubject.getText();
        String age = passedAge.getText();
        Person p = new Person(name, show, subject, age);
        
        if(txtField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(txtField1, "Please enter a guess");
        }else if(txtField1.getText().equalsIgnoreCase("bench")){
            JOptionPane.showMessageDialog(txtField1, "Your answer is correct!");
        }else if(txtField1.getText().equalsIgnoreCase("a bench")){
            JOptionPane.showMessageDialog(txtField1, "Your answer is correct!");            
        }else{
            JOptionPane.showMessageDialog(txtField1, "Your answer is incorrect. Try again!");
            txtField1.setText("");
            
            if(txtField1.getText().equalsIgnoreCase("bench") || txtField1.getText().equalsIgnoreCase("a bench")){
                JOptionPane.showMessageDialog(txtField1, "Your answer is correct!");
            }
        }
    }//GEN-LAST:event_txtField1ActionPerformed

    private void txtField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField2ActionPerformed
        String name = passedName.getText();
        String show = passedShow.getText();
        String subject = passedSubject.getText();
        String age = passedAge.getText();
        Person p = new Person(name, show, subject, age);
        
        if(txtField2.getText().isEmpty()){
            JOptionPane.showMessageDialog(txtField2, "Please enter a guess");
        }else if(txtField2.getText().equalsIgnoreCase("fence")){
            JOptionPane.showMessageDialog(txtField2, "Your answer is correct!");
        }else if(txtField2.getText().equalsIgnoreCase("a fence")){
            JOptionPane.showMessageDialog(txtField2, "Your answer is correct!");
        }else if(txtField2.getText().equalsIgnoreCase("gate")){
            JOptionPane.showMessageDialog(txtField2, "Your answer is correct!");
        }else if(txtField2.getText().equalsIgnoreCase("a gate")){
            JOptionPane.showMessageDialog(txtField2, "Your answer is correct!");
        }else{
            JOptionPane.showMessageDialog(txtField2, "Your answer is incorrect. Try again!");
            txtField2.setText("");
            
            if(txtField2.getText().equalsIgnoreCase("fence") || txtField2.getText().equalsIgnoreCase("a fence") || txtField2.getText().equalsIgnoreCase("gate") || txtField2.getText().equalsIgnoreCase("a gate")){
                JOptionPane.showMessageDialog(txtField2, "Your answer is correct!");
            }
        }
    }//GEN-LAST:event_txtField2ActionPerformed

    private void txtField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField3ActionPerformed
        String name = passedName.getText();
        String show = passedShow.getText();
        String subject = passedSubject.getText();
        String age = passedAge.getText();
        Person p = new Person(name, show, subject, age);
        
        if(txtField3.getText().isEmpty()){
            JOptionPane.showMessageDialog(txtField3, "Please enter a guess");
        }else if(txtField3.getText().equalsIgnoreCase("rope")){
            JOptionPane.showMessageDialog(txtField3, "Your answer is correct!");
        }else if(txtField3.getText().equalsIgnoreCase("a rope")){
            JOptionPane.showMessageDialog(txtField3, "Your answer is correct!");
        }else{
            JOptionPane.showMessageDialog(txtField3, "Your answer is incorrect. Try again!");
            txtField3.setText("");
            
            if(txtField3.getText().equalsIgnoreCase("rope") || txtField3.getText().equalsIgnoreCase("a rope")){
                JOptionPane.showMessageDialog(txtField3, "Your answer is correct!");
            }
        }
    }//GEN-LAST:event_txtField3ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Park2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Park2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Park2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Park2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Park2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToHomeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passedAge;
    private javax.swing.JLabel passedName;
    private javax.swing.JLabel passedShow;
    private javax.swing.JLabel passedSubject;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextArea txtAreaR1;
    private javax.swing.JTextArea txtAreaR2;
    private javax.swing.JTextArea txtAreaR3;
    private javax.swing.JTextArea txtAreaR4;
    private javax.swing.JTextField txtField1;
    private javax.swing.JTextField txtField2;
    private javax.swing.JTextField txtField3;
    private javax.swing.JTextField txtField4;
    // End of variables declaration//GEN-END:variables
}
