//guessing game
//holidays:
/*
    Christmas
    Halloween
    Fourth of July
    Thanksgiving
    New Year's Eve
    Easter
*/

package Storytime;

import OpeningChapter.Coverpage;
import OpeningChapter.FirstPage;
import business.Person;
import business.RandomObject;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class Storytime3 extends javax.swing.JFrame {

    
    public Storytime3() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public Storytime3(Person p){
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        String name = p.getName();
        String show = p.getShow();
        String subject = p.getSubject();
        String age = p.getAge();
        
        
        passedName.setText(name);
        passedShow.setText(show);
        passedSubject.setText(subject);
        passedAge.setText(age);
        
        txtArea1.setText("  All this talk about sweaters is "
                + "\n  reminding me of the holidays!"
                + "\n  If I put a few of the letters of a "
                + "\n  holiday down in the black box,"
                + "\n  do you think you can guess the holiday??");
        
        RandomObject o = new RandomObject();
        RandomObject b = o.getRandomHoliday();
        
        String nameCompare = b.getRHolidayName();
        String shortName = o.getRHoliday();
        
        nmCompare.setText(nameCompare);
        
        sName.setText(shortName);
        
        txtArea2.setText(shortName);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backToHomeButton = new javax.swing.JButton();
        txtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtArea2 = new javax.swing.JTextArea();
        txtArea1 = new javax.swing.JTextArea();
        passedName = new javax.swing.JLabel();
        passedShow = new javax.swing.JLabel();
        passedSubject = new javax.swing.JLabel();
        passedAge = new javax.swing.JLabel();
        nmCompare = new javax.swing.JTextField();
        sName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Your Guess:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 200, 40));

        backToHomeButton.setBackground(new java.awt.Color(0, 0, 102));
        backToHomeButton.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        backToHomeButton.setForeground(new java.awt.Color(255, 255, 255));
        backToHomeButton.setText("Back to Home");
        backToHomeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 6));
        backToHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToHomeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backToHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 110, 300, 80));

        txtField.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 270, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningChapter/Photos/christmas.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 400, 410));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningChapter/Photos/Thanksgiving.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 630, 220));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningChapter/Photos/halloween.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 300, 280));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningChapter/Photos/fourthjuly.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 320, 400, 440));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 40, 130, 130));

        txtArea2.setBackground(new java.awt.Color(0, 0, 0));
        txtArea2.setColumns(20);
        txtArea2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtArea2.setForeground(new java.awt.Color(255, 255, 255));
        txtArea2.setRows(5);
        txtArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 6));
        jPanel1.add(txtArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 270, 80));

        txtArea1.setBackground(new java.awt.Color(153, 255, 153));
        txtArea1.setColumns(20);
        txtArea1.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        txtArea1.setForeground(new java.awt.Color(255, 255, 255));
        txtArea1.setRows(5);
        txtArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 6));
        jPanel1.add(txtArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 30, 600, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 830));

        passedName.setText("passedName");
        getContentPane().add(passedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        passedShow.setText("passedShow");
        getContentPane().add(passedShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        passedSubject.setText("passedSubject");
        getContentPane().add(passedSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        passedAge.setText("passedAge");
        getContentPane().add(passedAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        nmCompare.setText("nmCompare");
        getContentPane().add(nmCompare, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 240, -1, -1));

        sName.setText("sName");
        getContentPane().add(sName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomeButtonActionPerformed
        new Coverpage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backToHomeButtonActionPerformed

    private void txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldActionPerformed
        RandomObject o = new RandomObject();
      
        String name = passedName.getText();
        String show = passedShow.getText();
        String subject = passedSubject.getText();
        String age = passedAge.getText();
        Person p = new Person(name, show, subject, age);
        String nameCompare = nmCompare.getText();
        String shortName = sName.getText();
                
        if(txtField.getText().equalsIgnoreCase(nameCompare)){
            JOptionPane.showMessageDialog(txtField, "Your answer is correct!");
            RandomObject r = new RandomObject();
            r.getRandomEnding(p);
            this.setVisible(false);
        }else if(txtField.getText().isEmpty()){
            JOptionPane.showMessageDialog(txtField, "Please enter a guess");
        }else{
            JOptionPane.showMessageDialog(txtField, "Your answer is incorrect! Try again");
            txtField.setText("");
            
            if(txtField.getText().equalsIgnoreCase(nameCompare)){
            JOptionPane.showMessageDialog(txtField, "Your answer is correct!");
            RandomObject r = new RandomObject();
            r.getRandomEnding(p);
            this.setVisible(false);
        }
        }
    }//GEN-LAST:event_txtFieldActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Storytime3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Storytime3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Storytime3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Storytime3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Storytime3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToHomeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nmCompare;
    private javax.swing.JLabel passedAge;
    private javax.swing.JLabel passedName;
    private javax.swing.JLabel passedShow;
    private javax.swing.JLabel passedSubject;
    private javax.swing.JTextField sName;
    private javax.swing.JTextArea txtArea1;
    private javax.swing.JTextArea txtArea2;
    private javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables
}
