//riddle
//answer: "sweater" OR "a sweater"

package Storytime;

import OpeningChapter.Coverpage;
import business.Person;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Storytime2 extends javax.swing.JFrame {

    public Storytime2() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public Storytime2(Person p){
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        String name = p.getName();
        String show = p.getShow();
        String subject = p.getSubject();
        String age = p.getAge();
        
        
        passedName.setText(name);
        passedShow.setText(show);
        passedSubject.setText(subject);
        passedAge.setText(age);
        
        txtArea.setText("Try to answer this riddle:"
                + "\nYou go in through one hole."
                + "\nYou come out through three holes."
                + "\nOnce you're inside, you're ready to go outside,"
                + "\nbut once you're outside, you're still inside."
                + "\nWhat am I???");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtField = new javax.swing.JTextField();
        BTHButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        passedName = new javax.swing.JLabel();
        passedShow = new javax.swing.JLabel();
        passedSubject = new javax.swing.JLabel();
        passedAge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningChapter/Photos/cj1.JPG"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 10), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 700, 660));

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        txtArea.setRows(5);
        txtArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jPanel1.add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 660, 290));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Your Guess:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 380, 250, 40));

        txtField.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 6));
        txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 460, 330, 70));

        BTHButton.setBackground(new java.awt.Color(255, 102, 102));
        BTHButton.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        BTHButton.setText("Back to Home");
        BTHButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTHButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BTHButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 670, 250, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel3.setText("?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 510, 70, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel4.setText("?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 420, 70, 80));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabel5.setText("?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 480, 70, 80));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel6.setText("?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 510, 70, 80));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel7.setText("?");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 70, 90));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabel8.setText("?");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 70, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 830));

        passedName.setText("passedName");
        getContentPane().add(passedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        passedShow.setText("passedShow");
        getContentPane().add(passedShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        passedSubject.setText("passedSubject");
        getContentPane().add(passedSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        passedAge.setText("passedAge");
        getContentPane().add(passedAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldActionPerformed
        String name = passedName.getText();
        String show = passedShow.getText();
        String subject = passedSubject.getText();
        String age = passedAge.getText();
        Person p = new Person(name, show, subject, age);
        
        if(txtField.getText().isEmpty()){
            JOptionPane.showMessageDialog(txtField, "Please enter a guess");
        }else if(txtField.getText().equalsIgnoreCase("sweater")){
            JOptionPane.showMessageDialog(txtField, "Your answer is correct!");
            
            new Storytime3(p).setVisible(true);
            this.setVisible(false);
        }else if(txtField.getText().equalsIgnoreCase("a sweater")){
            JOptionPane.showMessageDialog(txtField, "Your answer is correct");
            
            new Storytime3(p).setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(txtField, "Your answer is incorrect. Try again!");
            txtField.setText("");
            
            if(txtField.getText().equalsIgnoreCase("sweater") || txtField.getText().equalsIgnoreCase("a sweater")) {
                JOptionPane.showMessageDialog(txtField, "Your answer is correct!");
                
                new Storytime3(p).setVisible(true);
                this.setVisible(false);
            }
        }
        //not opening Storytime3 page after correct answer guessed
    }//GEN-LAST:event_txtFieldActionPerformed

    private void BTHButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTHButtonActionPerformed
        new Coverpage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTHButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Storytime2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Storytime2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Storytime2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Storytime2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Storytime2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTHButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passedAge;
    private javax.swing.JLabel passedName;
    private javax.swing.JLabel passedShow;
    private javax.swing.JLabel passedSubject;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables
}
